### ISSUE TITLE
Sleep only accepts integer

### ISSUE THREAD

**Issue by valerio-bozzolan** [neandrake/phab-dev#1]
Hi :)

Thanks for this repo

Hoping to be useful I noticed a small issue:

https://github.com/neandrake/phab-dev/blob/f837bbb130588360907d62b4b24fc05e35653135/phab-container/conf/entrypoint.sh#L28

Decimals are not allowed in sleep

https://www.man7.org/linux/man-pages/man1/sleep.1.html

**Comment by neandrake** [comment]
It is supported by sleep. The documentation states that the value does NOT need to be an integer.  I’ve used decimal values for sleep before for just such things (awaiting services starting).

> NUMBER need not be an integer.

**Comment by valerio-bozzolan** [comment]
Uuh nice! thanks and sorry :)
